version: '3'
services: 
  #build the dockerfile
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - db
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:

